server:
  host: "localhost"
  port: 8081
  corsOrigin: "http://localhost:5500"

# Database Credentials
database:
  host: "localhost"
  name: "user_db"
  user: "bipen"
  password: "mypassword"
  port: 5432

auth:
  jwtkey: "my_jwt_secret"

pagination:
  Limit : 5
  defaultpage: 1